### ISSUE TITLE
how can i call runAxeTest in my test?

### ISSUE THREAD

**Issue by BlancheYap** [E1Edatatracker/protractor-axe-report-plugin#2]
I tried using your sample after installing and adding plugin config in my protractor config file but i can't use runAxeTest maybe there's some configuration that i've missed

**Comment by ghost** [comment]
@sachams Same the above issue. Please look into

**Comment by sachams** [comment]
Hi,

Were you able to get your protractor tests working without enabling the plugin?

Also, what error messages are you getting?

**Comment by ghost** [comment]
@sachams Yes. i could able to run the test with and without this plugin integration. I had followed your documentation and I called the functions runAxeTest inside my step definitions. When I run the script I see and error as :TypeError: runAxeTest is not a function and my console shows 

**Code :** 
let runAxeTest = require('protractor-axe-report-plugin');
runAxeTest('Signin page', browser.driver); 

**Console Output** 

TypeError: runAxeTest is not a function

--- Accessibilty test results by standard ---
No filters specified - reporting on all standards

--- Accessibilty test results by page ---
No filters specified - reporting on all standards

**Comment by sachams** [comment]
You shouldn't have to add in a `require` line for the plug-in. Here's my code for a sign-in screen:

```js
var SigninPage = require('./signin.page');

describe('signin', function() {
  var signinPage = new SigninPage();
  
  beforeEach(function() {
    browser.get(signinPage.signinUrl);
  });

  it('Check accessibility', function() {
    runAxeTest('Signin page', browser.driver);
  });
});
```

**Comment by bwmatson** [comment]
@sachams I am having the same issues mentioned in this thread and tried importing "runAxeTest" from the npm package with no luck. Is "runAxeTest" supposed to be exported in the npm package's index.js?

**Comment by Chuvisco88** [comment]
There is definitely missing the part of making `runAxeTest` available to the tests, as it is not found automatically

```[08:40:13] E/launcher - Error: TSError: ⨯ Unable to compile TypeScript
e2e/app.e2e-spec.ts (60,7): Cannot find name 'runAxeTest'. (2304)```

It worked for me, when I added `const axeReportPlugin = require('protractor-axe-report-plugin');` and called it with `axeReportPlugin.runAxeTest('Signin page', browser.driver);`

**Comment by Chuvisco88** [comment]
@sachams I have the same issue, tried your example and got this error: `Cannot find name 'runAxeTest'.`
How is the function made available to your tests?

**Comment by Phonesis** [comment]
Any update on this? Seems no answer was ever provided

**Comment by saidu23** [comment]
@sachams Getting same error Failed: runAxeTest is not defined. Any help??

**Comment by Nagadinesh** [comment]
Anyone able to figure it out?

**Comment by havrda** [comment]
This is not a good thing. But I added this to the index.js of the plugin package in node_modules:
exports.runAxeTest = runAxeTest;

Then in my test I added an import:
import { runAxeTest } from 'protractor-axe-report-plugin'; 

Obviously a horrible solution. But that did make it work.

**Comment by sthonape** [comment]
How can Use this plugin with Protractor TypeScript
